"""
Data Schemas for Fact Knowledge Layer
======================================
Defines Pydantic models for:
- Document and page metadata
- Exact source evidence grounding
- Structured facts (numerical and semantic)
- Cross-document relationship classifications (CORROBORATES, CONTRADICTS, RECONCILES)
"""

from enum import Enum
from typing import Optional, Dict, Any
from pydantic import BaseModel, Field


class FactType(str, Enum):
    """Classification of the nature of an extracted fact."""
    NUMERICAL = "NUMERICAL"       # e.g., Financial figures, counts, percentages, metrics
    SEMANTIC = "SEMANTIC"         # e.g., Statements, descriptions, qualitative assertions
    TEMPORAL = "TEMPORAL"         # e.g., Dates, tenure, effective periods, milestones
    ENTITY_STATUS = "ENTITY_STATUS" # e.g., Active director, resigned, incorporated


class RelationshipType(str, Enum):
    """
    Cross-document relationship types defined for the assignment:
    - CORROBORATES: Same fact expressed differently across documents.
    - CONTRADICTS: Same subject/predicate/context but with conflicting values.
    - RECONCILES: Facts appear contradictory but can be explained by context (e.g. time period, scope, units).
    """
    CORROBORATES = "CORROBORATES"
    CONTRADICTS = "CONTRADICTS"
    RECONCILES = "RECONCILES"


class Evidence(BaseModel):
    """
    Source grounding for an extracted fact.
    Every fact must trace back to its exact evidence in the source document.
    """
    document_name: str = Field(..., description="Name of the source PDF document.")
    page_number: int = Field(..., description="1-indexed page number where the fact appears.")
    quote: str = Field(..., description="Exact verbatim text snippet from the document page supporting this fact.")
    context_snippet: Optional[str] = Field(
        default=None,
        description="Surrounding paragraph or sentence providing contextual scope."
    )


class Fact(BaseModel):
    """
    Structured representation of an extracted fact.
    Can represent numerical, semantic, or entity-state information with full provenance.
    """
    id: Optional[int] = Field(default=None, description="Unique identifier for the fact in storage.")
    document_id: Optional[int] = Field(default=None, description="Foreign key to the source document.")
    document_name: str = Field(..., description="Name of the source document.")
    page_number: int = Field(..., description="Source page number.")
    
    # Core semantic triple representation
    subject: str = Field(..., description="Entity or topic the fact is about (e.g., 'Acme Corp Revenue', 'John Doe').")
    predicate: str = Field(..., description="Attribute or relationship (e.g., 'reported annual revenue of', 'held position of').")
    object_value: str = Field(..., description="Raw or formatted value (e.g., '$10.5 million', 'Director').")
    
    # Optional normalized attributes
    fact_type: FactType = Field(default=FactType.SEMANTIC, description="Type of fact (numerical, semantic, etc.).")
    numeric_value: Optional[float] = Field(default=None, description="Normalized numeric value if applicable.")
    unit: Optional[str] = Field(default=None, description="Unit of measurement (e.g., 'USD', '%', 'employees').")
    time_period: Optional[str] = Field(default=None, description="Applicable timeframe (e.g., 'FY2023', 'Q1 2024').")
    context: Optional[str] = Field(default=None, description="Qualifying context, scope, or accounting standard.")
    
    # Grounding & confidence
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Extraction confidence score.")
    evidence: Evidence = Field(..., description="Exact source grounding supporting this fact.")

    @property
    def value(self) -> str:
        """Alias for object_value."""
        return self.object_value

    @property
    def time_context(self) -> Optional[str]:
        """Alias for time_period."""
        return self.time_period

    @property
    def scope_context(self) -> Optional[str]:
        """Alias for context."""
        return self.context


class ExtractedFactItem(BaseModel):
    """
    Structured extraction payload generated by the LLM for each factual claim on a page.
    Directly aligns with the assignment extraction requirements.
    """
    subject: str = Field(..., description="Entity or topic the fact is about.")
    predicate: str = Field(..., description="Action, state, or attribute asserted.")
    value: str = Field(..., description="The asserted value, metric, or status (e.g. '$12.5M', 'Resigned').")
    fact_type: FactType = Field(default=FactType.SEMANTIC, description="Classification: NUMERICAL, SEMANTIC, TEMPORAL, ENTITY_STATUS.")
    numeric_value: Optional[float] = Field(default=None, description="Normalized numeric value if numerical fact.")
    unit: Optional[str] = Field(default=None, description="Unit of measurement if applicable (e.g. 'USD', '%', 'employees').")
    time_context: Optional[str] = Field(default=None, description="Time period or date (e.g. 'FY2023', 'Q3 2024').")
    scope_context: Optional[str] = Field(default=None, description="Scope, boundary, or qualifiers (e.g. 'Consolidated', 'US operations').")
    evidence_quote: str = Field(..., description="Exact verbatim text span from the page supporting this fact.")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0.")

    def to_fact(self, document_name: str, page_number: int, document_id: Optional[int] = None) -> "Fact":
        """Converts extracted item into the persistent Fact domain model."""
        return Fact(
            document_id=document_id,
            document_name=document_name,
            page_number=page_number,
            subject=self.subject.strip(),
            predicate=self.predicate.strip(),
            object_value=self.value.strip(),
            fact_type=self.fact_type,
            numeric_value=self.numeric_value,
            unit=self.unit.strip() if self.unit else None,
            time_period=self.time_context.strip() if self.time_context else None,
            context=self.scope_context.strip() if self.scope_context else None,
            confidence=float(self.confidence),
            evidence=Evidence(
                document_name=document_name,
                page_number=page_number,
                quote=self.evidence_quote.strip(),
                context_snippet=self.scope_context.strip() if self.scope_context else None,
            )
        )


class ExtractedFactsList(BaseModel):
    """Container for structured response parsing from Gemini."""
    facts: list[ExtractedFactItem] = Field(default_factory=list, description="List of factual claims found on the page.")


class FactRelationship(BaseModel):
    """
    Comparison relationship identified between two facts across documents.
    """
    id: Optional[int] = Field(default=None, description="Unique identifier for the relationship record.")
    fact_a_id: int = Field(..., description="ID of the first fact being compared.")
    fact_b_id: int = Field(..., description="ID of the second fact being compared.")
    relationship_type: RelationshipType = Field(
        ...,
        description="Classification: CORROBORATES, CONTRADICTS, or RECONCILES."
    )
    reasoning: str = Field(
        ...,
        description="System's reasoning explaining why the relationship holds based on evidence."
    )
    reconciliation_context: Optional[str] = Field(
        default=None,
        description="For RECONCILES: The specific dimension (e.g., time period, scope, units) that reconciles them."
    )
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence in the relationship assessment.")


class DocumentMetadata(BaseModel):
    """Metadata for an uploaded document."""
    id: Optional[int] = None
    filename: str
    total_pages: int
    uploaded_at: Optional[str] = None
    file_path: Optional[str] = None


class DocumentPage(BaseModel):
    """Extracted text and metadata for a single page of a document."""
    id: Optional[int] = None
    document_id: int
    page_number: int
    text: str
    char_count: int
